### ISSUE TITLE
Get icons and social media links for footer

### ISSUE THREAD

**Issue by pmotch** [open-voice-network/website#2]
- [x] Get GitHub SVG icon
- [x] Get LinkedIn SVG icon
- [x] Add link for Facebook
- [x] Add link for LinkedIn

Once @frickealissa has the links for Facebook and LinkedIn, I can add them to the footer.

**Comment by frickealissa** [comment]
Hi @pmotch! Here are the links:
https://www.facebook.com/Open-Voice-Network-103375474336837/
https://www.linkedin.com/company/open-voice-network

**Comment by pmotch** [comment]
Done
