### ISSUE TITLE
Domain extension on about page is wrong

### ISSUE THREAD

**Issue by uselessgames** [open-voice-network/website#73]
**- Do you want to request a *feature* or report a *bug*?**
it's sort of a bug

**- What is the current behavior?**
the domain extension on the github repo about section reads **.com**

**- If the current behavior is a bug, please provide the steps to reproduce.**
go to https://github.com/open-voice-network/website and read the about section to see the wrong domain, when clicked it goes nowhere.
![image](https://user-images.githubusercontent.com/66875544/124562724-a657a600-de3f-11eb-801e-f8a3eb96a229.png)

**- What is the expected behavior?**
the correct domain extension is **.org**  `https://openvoicenetwork.org/`

**- Please mention your node.js, NPM, Hugo and operating system version.**
My name is not Hugo ;)

**Comment by pmotch** [comment]
Thanks for catching that and submitting an issue! I just fixed it to `.org`.
